### PR TITLE
🥅 Capture exception, when thrown while setting up streams during OrleansHubLifetimeManager startup and reset providers and streams.

### PR DESCRIPTION
**Pull request by SilentBlueD666**
When the OrleansHubLifetimeManager is setting up streams, getting the provider can be successful, however creating stream subscriptions can fail, this leaves the manager in a dead state, as the method EnsureStreamSetup checks if _streamProvider is null, where it will not be, therefore no messages are received from Grains running in an external Silo.

This PR will log the error and reset the variables the SetupStream methods tries to initialize to null, so that the next time, the EnsureStreamSetup method tries again.

### CODE REVIEW

**Comment by stephenlautier** [comment]
Thanks for the PR, which version are you using? 4.x?

**Comment by stephenlautier** [comment]
And this generally happens when misconfigured most probably? or somehow also can trigger when configured correctly?

**Comment by SilentBlueD666** [comment]
Hi, thanks for the quick response 😁

I am using version `5.0.0-dev.153` 

I thought was missed configured too, but all was good from what could see... as it's really simple 😉 

When debugging I get a `Null` exception when SetupStream sets '_serverStreamsReplicaContainer' it's because the queueAdapter in 'PersistentStreamProvider'  is null at this point when it first starts up ('Init' has not yet run, my break point here does run later and the 'queueAdapter' is set).

I think the main problem is timing, the cluster client is not fully active when the OrleansHubLifetimeManager is created (my Silo is hosted in another process), my hope here is that the error is logged and then when the first user connects the Setup will run again but this time the cluster client will be ready... Currently this does not happen because '_streamProvider' is not null and therefore thinks the 'OrleansHubLifetimeManager' is initialized.

**Review by stephenlautier — APPROVED** [review]

**Comment by stephenlautier** [comment]
Published in 5.0.0-dev.155

**Comment by SilentBlueD666** [comment]
Thanks that's brilliant 😁

**Pull request merged**
